# Generated by Django 4.1.5 on 2023-02-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photo', verbose_name='Фото')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='Адрес')),
                ('age', models.CharField(blank=True, max_length=3, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, max_length=8, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
