# Generated by Django 4.1.5 on 2023-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='not img', upload_to='photo', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='not price', max_length=20, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
