# Generated by Django 4.1.5 on 2023-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_photo_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
